- name: create download dir
  file: path="/tmp/.ansible/files" state=directory

- name: download tar file
  get_url:
    url: "https://github.com/coreos/etcd/releases/download/v{{ etcd_version }}/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
    dest: /tmp/.ansible/files

- name: extract tar file
  unarchive:
    src: "/tmp/.ansible/files/etcd-v{{ etcd_version }}-linux-amd64.tar.gz"
    dest: /opt
    copy: no

- name: create symlinks
  file:
    src: /opt/etcd-v{{ etcd_version }}-linux-amd64/{{ item }}
    dest: /usr/local/bin/{{ item }}
    state: link
  with_items:
    - etcd
    - etcdctl

- name: copy systemd service
  copy: src=etcd.service dest=/etc/systemd/system
  notify: reload systemd

- name: create config directory
  file: path="/etc/etcd" state=directory
