
- name: get etcd version
  command: /usr/local/bin/etcd --version
  register: etcd_detected_version
  ignore_errors: yes

- name: enable etcd user
  user: name=etcd comment=etcd createhome=no shell=/bin/false

- name: ensure valid etcd data directory
  file: path="{{ etcd_data_dir }}" state=directory owner=etcd group=etcd recurse=True

- include: install.yml
  when: etcd_detected_version.rc != 0 or etcd_detected_version.stdout.find(etcd_version) == -1
  notify: restart etcd

- name: write etcd config file
  template: src=etcd.j2 dest=/etc/sysconfig/etcd
  notify: restart etcd

- name: enable etcd
  service: name=etcd enabled=yes
