
etcd_initial_cluster_token: "{{ dc }}-kubernetes"
etcd_initial_cluster_state: new
etcd_proxy: True
etcd_initial_advertise_peer_urls: "http://{{ inventory_hostname }}:{{ etcd_peer_port }}"
etcd_listen_peer_urls: "http://0.0.0.0:{{ etcd_peer_port }}"
etcd_advertise_client_urls: "http://{{ inventory_hostname }}:{{ etcd_client_port }}"
etcd_listen_client_urls: "http://0.0.0.0:{{ etcd_client_port }}"
flannel_etcd_key: "/{{ dc }}-kubernetes/network"
flannel_subnet: 192.168.0.0/12
