
- name: Install flannel
  yum: name=flannel state=present
  notify: Restart flannel

- name: Install Flannel config file
  template: src=flanneld.j2 dest=/etc/sysconfig/flanneld
  notify: Restart flannel

- name: Enable flannel
  service: name=flannel enabled=yes

- name: Start flannel
  service: name=flannel state=started
