
- name: add docker repository
  copy: src=docker.repo dest=/etc/yum.repos.d/docker.repo

- name: install docker-engine
  yum: name=docker-engine state=present
  notify: restart docker

- name: copy systemd service
  template: src=docker.service.j2 dest=/etc/systemd/system/docker.service
  notify:
    - reload systemd
    - restart docker

- name: enable docker
  service: name=docker enabled=yes
