
etcd_version: "2.2.0"
etcd_proxy: False
etcd_client_port: 2379
etcd_peer_port: 2380
etcd_peers_group: etcd
etcd_conf_dir: /etc/etcd
etcd_script_dir: /usr/libexec/etcd
etcd_ca_file: "{{ etcd_conf_dir }}/ca.crt"
etcd_cert_file: "{{ etcd_conf_dir }}/server.crt"
etcd_key_file: "{{ etcd_conf_dir }}/server.key"
etcd_peer_ca_file: "{{ etcd_ca_file }}"
etcd_peer_cert_file: "{{ etcd_conf_dir }}/peer.crt"
etcd_peer_key_file: "{{ etcd_conf_dir }}/peer.key"

etcd_initial_cluster_state: new
etcd_initial_cluster_token: kubernetes
etcd_initial_advertise_peer_urls: "http://{{ inventory_hostname }}:{{ etcd_peer_port }}"
etcd_listen_peer_urls: "http://0.0.0.0:{{ etcd_peer_port }}"
etcd_advertise_client_urls: "http://{{ inventory_hostname }}:{{ etcd_client_port }}"
etcd_listen_client_urls: "http://0.0.0.0:{{ etcd_client_port }}"

etcd_data_dir: /var/lib/etcd
